//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2017-02-10 19:58:39 by 诸葛冷冷
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace Tmp.Model
{
	[Table("Quarterly Orders")]
	[Serializable]
    public class Quarterly_Orders : BaseEntity
	{
		[Column("City")]
		[StringLength(15, ErrorMessage = "{0}不能超过15个字符")]
		[Display(Name = "字段中文名称，实际使用时，需改")]
		public string City { get; set; }

		[Column("CompanyName")]
		[StringLength(40, ErrorMessage = "{0}不能超过40个字符")]
		[Display(Name = "字段中文名称，实际使用时，需改")]
		public string CompanyName { get; set; }

		[Column("Country")]
		[StringLength(15, ErrorMessage = "{0}不能超过15个字符")]
		[Display(Name = "字段中文名称，实际使用时，需改")]
		public string Country { get; set; }

		[Key]
		[Column("CustomerID")]
		[StringLength(5, ErrorMessage = "{0}不能超过5个字符")]
		[Display(Name = "字段中文名称，实际使用时，需改")]
		public string CustomerID { get; set; }

	}
}
