//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2017-02-10 12:22:57 by 诸葛冷冷
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using Tmp.Common.Tools.Helper;

namespace Tmp.Model
{
    [Table("CustomerDemographics")]
    [Serializable]
    public class CustomerDemographics : BaseEntity
    {
        
        [Key]
        [Column("CustomerTypeID")]
        [StringLength(10, ErrorMessage = "{0}不能超过10个字符")]
        [Required(ErrorMessage = "{0}不能为空")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string CustomerTypeID { get; set; }
        
        [Column("CustomerDesc")]
        [StringLength(8, ErrorMessage = "{0}不能超过8个字符")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string CustomerDesc { get; set; }

        /// <summary>
        /// 属性浅拷贝
        /// </summary>
        /// <returns></returns>
        public CustomerDemographics Clone()
        {
            return ObjectCopier.Clone<CustomerDemographics>(this);
        }
    }
}
