//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2017-02-10 12:22:57 by 诸葛冷冷
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using Tmp.Common.Tools.Helper;

namespace Tmp.Model
{
    [Table("Employees")]
    [Serializable]
    public class Employees : BaseEntity
    {
        
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int EmployeeID { get; set; }
        
        [Column("LastName")]
        [StringLength(20, ErrorMessage = "{0}不能超过20个字符")]
        [Required(ErrorMessage = "{0}不能为空")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string LastName { get; set; }
        
        [Column("FirstName")]
        [StringLength(10, ErrorMessage = "{0}不能超过10个字符")]
        [Required(ErrorMessage = "{0}不能为空")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string FirstName { get; set; }
        
        [Column("Title")]
        [StringLength(30, ErrorMessage = "{0}不能超过30个字符")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string Title { get; set; }
        
        [Column("TitleOfCourtesy")]
        [StringLength(25, ErrorMessage = "{0}不能超过25个字符")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string TitleOfCourtesy { get; set; }
        
        [Column("BirthDate")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public DateTime? BirthDate { get; set; }
        
        [Column("HireDate")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public DateTime? HireDate { get; set; }
        
        [Column("Address")]
        [StringLength(60, ErrorMessage = "{0}不能超过60个字符")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string Address { get; set; }
        
        [Column("City")]
        [StringLength(15, ErrorMessage = "{0}不能超过15个字符")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string City { get; set; }
        
        [Column("Region")]
        [StringLength(15, ErrorMessage = "{0}不能超过15个字符")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string Region { get; set; }
        
        [Column("PostalCode")]
        [StringLength(10, ErrorMessage = "{0}不能超过10个字符")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string PostalCode { get; set; }
        
        [Column("Country")]
        [StringLength(15, ErrorMessage = "{0}不能超过15个字符")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string Country { get; set; }
        
        [Column("HomePhone")]
        [StringLength(24, ErrorMessage = "{0}不能超过24个字符")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string HomePhone { get; set; }
        
        [Column("Extension")]
        [StringLength(4, ErrorMessage = "{0}不能超过4个字符")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string Extension { get; set; }
        
        [Column("Photo")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public byte[] Photo { get; set; }
        
        [Column("Notes")]
        [StringLength(8, ErrorMessage = "{0}不能超过8个字符")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string Notes { get; set; }
        
        [Column("ReportsTo")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public int? ReportsTo { get; set; }
        
        [Column("PhotoPath")]
        [StringLength(255, ErrorMessage = "{0}不能超过255个字符")]
        [Display(Name = "字段中文名称，实际使用时，需改")]
        public string PhotoPath { get; set; }

        /// <summary>
        /// 属性浅拷贝
        /// </summary>
        /// <returns></returns>
        public Employees Clone()
        {
            return ObjectCopier.Clone<Employees>(this);
        }
    }
}
